// 图表帮助文本配置（支持i18n）
export const chartHelpTexts = {
  zh: {
    wealthCurve: '展示每一轮后的平均资金变化。可以看到资金的增长轨迹和波动情况，直观反映策略的整体表现。',
    cumulativeReturn: '相对于初始资金的累计收益百分比变化。正值表示盈利，负值表示亏损。这是评估策略盈利能力的核心指标。',
    cumulativeDrawdown: '每一轮相对于历史峰值的回撤百分比。回撤越小，策略越稳健，风险控制越好。这是评估策略风险的重要指标。',
    rollingVolatility: '使用最近10轮的滚动窗口计算的波动率。反映短期风险水平的动态变化，波动率越高风险越大。',
    logReturn: '对数尺度下的资金变化。更适合观察长期复利增长，凯利公式就是最大化长期对数收益的策略。',
    returnDrawdownRatio: '累计收益除以最大回撤的比值。比值越高，说明承担相同回撤风险获得的收益越好，策略的风险调整后表现越优秀。',
    newHighs: '创造资金历史新高的累计次数。次数越多，说明策略持续盈利能力越强，能够不断突破前期高点。',
    relativeChange: '相对于初始资金的变化百分比。另一种展示累计收益的方式，更直观地反映资金增长或亏损的程度。',
    growthRate: '衡量每一轮资金相对于上一轮的变化百分比。正值表示增长，负值表示下降。',
    cumulativeProfit: '所有盈利轮次的累计盈利百分比之和。反映策略的总体盈利能力。',
    cumulativeLoss: '所有亏损轮次的累计亏损百分比之和（负值）。反映策略的总体风险暴露。',
    relativeDrawdown: '当前资金相对于历史峰值的回撤百分比。实时反映当前的风险状态。',
    peakWealth: '截至当前轮的历史最高资金。用于计算回撤和评估策略的历史最佳表现。',
    distanceFromPeak: '当前资金距离历史峰值的绝对金额差距。直观显示需要恢复多少资金才能回到峰值。',
    winRateRolling: '最近20轮中盈利轮次的占比。反映短期的胜率趋势，帮助判断策略近期表现。',
    avgProfitRolling: '最近20轮盈利轮次的平均盈利百分比。反映短期盈利轮次的平均收益水平。',
    avgLossRolling: '最近20轮亏损轮次的平均亏损百分比（负值）。反映短期亏损轮次的平均风险水平。',
    profitLossRatioRolling: '最近20轮的平均盈利除以平均亏损的绝对值。比值大于1说明盈利幅度大于亏损幅度。',
    sharpeRatioRolling: '最近30轮的风险调整后收益率。考虑了收益和波动性，越高说明单位风险获得的收益越好。',
    sortinoRatioRolling: '最近30轮的下行风险调整后收益率。只考虑下行波动，更关注亏损风险。比夏普比率更严格。',
    calmarRatio: '累计收益除以最大回撤。评估长期风险调整后收益，比值越高越好。',
    currentWinStreak: '当前连续盈利的轮数。反映策略当前的连胜状态。',
    currentLossStreak: '当前连续亏损的轮数。反映策略当前的连亏状态，需要警惕。',
    maxWinStreak: '历史上连续盈利的最长轮数。反映策略的最佳连胜记录。',
    maxLossStreak: '历史上连续亏损的最长轮数。反映策略的最大连续风险，需要关注。',
    recoveryIndex: '资金新高次数除以总轮数的比值。反映策略从回撤中恢复并创新高的能力。',
    var5Rolling: '最近50轮的5%分位数收益率。表示有5%的概率亏损超过此值，用于评估极端风险。',
    maxSingleProfit: '历史上单轮最大盈利百分比。反映策略的最大盈利潜力。',
    maxSingleLoss: '历史上单轮最大亏损百分比（负值）。反映策略的单轮最大风险。'
  },
  en: {
    wealthCurve: 'Shows average wealth change after each round. Visualizes growth trajectory and volatility, reflecting overall strategy performance.',
    cumulativeReturn: 'Cumulative return percentage relative to initial wealth. Positive values indicate profit, negative indicate loss. Core metric for evaluating strategy profitability.',
    cumulativeDrawdown: 'Drawdown percentage relative to historical peak for each round. Smaller drawdown indicates more stable strategy with better risk control.',
    rollingVolatility: 'Volatility calculated using a rolling 10-round window. Reflects dynamic changes in short-term risk level; higher volatility means higher risk.',
    logReturn: 'Wealth change on logarithmic scale. Better for observing long-term compound growth. Kelly formula maximizes long-term log returns.',
    returnDrawdownRatio: 'Ratio of cumulative return to maximum drawdown. Higher ratio indicates better return for the same drawdown risk, showing superior risk-adjusted performance.',
    newHighs: 'Cumulative count of creating new wealth highs. More occurrences indicate stronger sustained profitability and ability to breakthrough previous peaks.',
    relativeChange: 'Change percentage relative to initial wealth. Another way to display cumulative returns, more intuitively showing wealth growth or loss extent.',
    growthRate: 'Measures percentage change of wealth relative to previous round. Positive values indicate growth, negative indicate decline.',
    cumulativeProfit: 'Sum of cumulative profit percentages from all profitable rounds. Reflects overall profit-making capability of the strategy.',
    cumulativeLoss: 'Sum of cumulative loss percentages from all losing rounds (negative value). Reflects overall risk exposure of the strategy.',
    relativeDrawdown: 'Current wealth drawdown percentage relative to historical peak. Real-time reflection of current risk status.',
    peakWealth: 'Historical highest wealth up to current round. Used to calculate drawdown and evaluate strategy\'s historical best performance.',
    distanceFromPeak: 'Absolute amount difference between current wealth and historical peak. Intuitively shows how much wealth needs to be recovered to return to peak.',
    winRateRolling: 'Proportion of profitable rounds in the last 20 rounds. Reflects short-term win rate trend, helps judge recent strategy performance.',
    avgProfitRolling: 'Average profit percentage of profitable rounds in the last 20 rounds. Reflects average return level of short-term profitable rounds.',
    avgLossRolling: 'Average loss percentage of losing rounds in the last 20 rounds (negative value). Reflects average risk level of short-term losing rounds.',
    profitLossRatioRolling: 'Average profit divided by absolute value of average loss in the last 20 rounds. Ratio greater than 1 indicates profit magnitude exceeds loss magnitude.',
    sharpeRatioRolling: 'Risk-adjusted return for the last 30 rounds. Considers both return and volatility; higher values indicate better return per unit of risk.',
    sortinoRatioRolling: 'Downside risk-adjusted return for the last 30 rounds. Only considers downside volatility, more focused on loss risk. Stricter than Sharpe ratio.',
    calmarRatio: 'Cumulative return divided by maximum drawdown. Evaluates long-term risk-adjusted return; higher ratio is better.',
    currentWinStreak: 'Current consecutive profitable rounds. Reflects strategy\'s current winning streak status.',
    currentLossStreak: 'Current consecutive losing rounds. Reflects strategy\'s current losing streak status; needs caution.',
    maxWinStreak: 'Longest consecutive profitable rounds in history. Reflects strategy\'s best winning streak record.',
    maxLossStreak: 'Longest consecutive losing rounds in history. Reflects strategy\'s maximum consecutive risk; needs attention.',
    recoveryIndex: 'Ratio of new highs count to total rounds. Reflects strategy\'s ability to recover from drawdowns and create new highs.',
    var5Rolling: '5th percentile return of the last 50 rounds. Indicates 5% probability of loss exceeding this value; used to assess extreme risk.',
    maxSingleProfit: 'Historical maximum single-round profit percentage. Reflects strategy\'s maximum profit potential.',
    maxSingleLoss: 'Historical maximum single-round loss percentage (negative value). Reflects strategy\'s maximum single-round risk.'
  }
};

export type ChartHelpKey = keyof typeof chartHelpTexts.zh;
